=== Ivan1Perez/proyecto_2Evaluacion/travelpot.dtd
<!ELEMENT travelpot (usuarios, hoteles, reservas)>
<!ELEMENT usuarios (root, no_root*)>
<!ELEMENT root (usuario, contrasenya)>
<!ELEMENT no_root (nombre)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT contrasenya (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT hoteles (hotel*)>
<!ELEMENT hotel (nombre_hotel, ciudad, importe_habitacion)>
<!ELEMENT nombre_hotel (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT importe_habitacion (#PCDATA)>
<!ELEMENT reservas (reserva*)>
<!ELEMENT reserva (nombre_hotel, dia_entrada, dia_salida, nombre_reserva, importe_reserva)>
<!ELEMENT dia_entrada (#PCDATA)>
<!ELEMENT dia_salida (#PCDATA)>
<!ELEMENT nombre_reserva (#PCDATA)>
<!ELEMENT importe_reserva (#PCDATA)>

=== Ivan1Perez/proyecto_2Evaluacion/travelpot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- prueba -->
<!DOCTYPE travelpot SYSTEM "travelpot.dtd">
<travelpot>
    <usuarios>
        <!-- Solo hay uno-->
        <root>
            <usuario></usuario>
            <contrasenya></contrasenya>
        </root>
        <!-- Puede haber indefinidos-->
        <no_root>
            <nombre></nombre>
        </no_root>
    </usuarios>
    <hoteles>
        <!-- Puede haber indefinidos-->
        <hotel>
            <nombre_hotel></nombre_hotel>
            <ciudad></ciudad>
            <importe_habitacion></importe_habitacion>
        </hotel>
    </hoteles>
    <reservas>
        <!-- Puede haber indefinidos-->
        <reserva>
            <nombre_hotel></nombre_hotel>
            <dia_entrada></dia_entrada>
            <dia_salida></dia_salida>
            <nombre_reserva></nombre_reserva>
            <importe_reserva></importe_reserva>
        </reserva>
    </reservas>
</travelpot>
