<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE travelpot [
    <!ELEMENT travelpot (usuarios, hoteles, reservas)>
    <!ELEMENT usuarios (root, no_root*)>
    <!ELEMENT root (usuario, password)>
    <!ELEMENT no_root (nombre,apellidos,direccion,poblacion,provincia,email,usuario,password)>
    <!ELEMENT usuario (#PCDATA)>
    <!ELEMENT password (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT hoteles (hotel*)>
    <!ELEMENT hotel (nombre_hotel, ciudad, numHabitaciones, importe_habitacion)>
    <!ELEMENT nombre_hotel (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT numHabitaciones (#PCDATA)>
    <!ELEMENT importe_habitacion (#PCDATA)>
    <!ELEMENT reservas (reserva*)>
    <!ELEMENT reserva (nombre_hotel, dia_entrada, dia_salida, nombre_reserva, importe_reserva)>
    <!ELEMENT dia_entrada (#PCDATA)>
    <!ELEMENT dia_salida (#PCDATA)>
    <!ELEMENT nombre_reserva (#PCDATA)>
    <!ELEMENT importe_reserva (#PCDATA)>
]>

<travelpot>
    <usuarios>
        <!-- Solo hay uno-->
        <root>
            <usuario>root</usuario>
            <password>123456</password>
        </root>
        <!-- Puede haber indefinidos-->
        <no_root>
            <nombre>Ivan</nombre>
            <apellidos>Perez</apellidos>
            <direccion>Olocau</direccion>
            <poblacion>Valencia</poblacion>
            <provincia>Calle falsa 123</provincia>
            <email>ivan@gmail.es</email>
            <usuario>Iv</usuario>
            <password>4Cuatro!</password>
        </no_root>
        <no_root>
            <nombre>Test1</nombre>
            <apellidos>Test1Apellido</apellidos>
            <direccion>Invent1</direccion>
            <poblacion>XD</poblacion>
            <provincia>Mas Invent</provincia>
            <email>invent1@gmail.es</email>
            <usuario>Test1Usuario</usuario>
            <password>4Cuatro!</password>
        </no_root>
        <no_root>
            <nombre>Test2</nombre>
            <apellidos>Test2Apellido</apellidos>
            <direccion>Invent2</direccion>
            <poblacion>XD</poblacion>
            <provincia>Mas Invent</provincia>
            <email>invent2@gmail.es</email>
            <usuario>Test2Usuario</usuario>
            <password>4Cuatro!</password>
        </no_root>
    </usuarios>
    <hoteles>
        <!-- Puede haber indefinidos-->
        <hotel>
            <nombre_hotel>Ad Hoc Monumental 1881</nombre_hotel>
            <ciudad>Valencia</ciudad>
            <numHabitaciones>1</numHabitaciones>
            <importe_habitacion>60</importe_habitacion>
        </hotel>
    </hoteles>
    <reservas>
        <!-- Puede haber indefinidos-->
        <reserva>
            <nombre_hotel></nombre_hotel>
            <dia_entrada></dia_entrada>
            <dia_salida></dia_salida>
            <nombre_reserva></nombre_reserva>
            <importe_reserva></importe_reserva>
        </reserva>
    </reservas>
</travelpot>